### ISSUE TITLE
Request for executable

### ISSUE THREAD

**Issue by AussieGlenn** [malcrom/WaypointCreator#10]
Hi,

Is it possible to have a download for an executable like WPP please?

The MSCharts addon is problematic to get working, and it will not compile without it.

Thanks,

Glenn

**Comment by Saben65** [comment]
You shouldn't need to compile anything. Click and drag the .pkt file onto the Waypoint Creator.exe located in WaypointCreator-master\Waypoint Creator\bin\Release

**Comment by AussieGlenn** [comment]
Hi Saben65,

I see it. Fantastic.

I have loaded in a text sniff. i hit search on the right hand side and it shows me every path visually in the main frame.

It connects to the database correctly.

However, in the SQL Output tab, it shows nothing.

Could you help me on how I get the SQL Output to work please?

Thanks,

Glenn

**Comment by AussieGlenn** [comment]
Thanks so much
