### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Kittnz** [malcrom/WaypointCreator#2]
- Map.
- Delay of next path. ( we have the time stamp, so maybe just calculate how many seconds, mili seconds between next waypoint? ).
- Option to for only TDB or UDB sql output.

That's it for now, great work here malcrom!
Gonna safe us tons of time!

**Comment by Kittnz** [comment]
Woh this is old 💃

**Comment by Rushor** [comment]
old but gold <3
