### ISSUE TITLE
multiple creatures wp

### ISSUE THREAD

**Issue by soulfrost** [malcrom/WaypointCreator#5]
it's imposible to extract WP for all creatures exist in parsed sniff by map id ?

**Comment by Kittnz** [comment]
If the sniff has enough information you can extract all wp for each creature soulfrost.
You cannot extract it automaticly, you will have to check each waypoint for the right way and sometimes delete or remove some points.

**Comment by Rushor** [comment]
..and sometimes delete or remove some points.

Thats exaklty the problem at the moment :/
I wonder if there would be any possibility to add own points over the existing ones - you would be able to create your own path then (something like this: http://www.bilder-upload.eu/show.php?file=62a9dc-1433333460.png)

**Comment by Kittnz** [comment]
@Rushor then it's not blizzlike if you add more points then needed, also you need a map to make paths then.

**Comment by Rushor** [comment]
i tried to say that we need a way to reduce the number of parsed waypoints

maybe only a selection of the most important points

in other words:
(example with http://www.bilder-upload.eu/show.php?file=62a9dc-1433333460.png)
- select point 1, 5, 10, 17, 33, 42, 51, 65, 73, 81, 95, 106, 114
- hit a button which selects these few points and reorganises it to the normal order aka 1,2,3.. and automatically creates the sql


big wishes i know - but it would make the work much easier the the path would look much smoother

**Comment by malcrom** [comment]
This tool is for extracting from sniffs. Not adding your own points.

**Comment by Rushor** [comment]
yes thanks for explaining the cut button :)
