### ISSUE TITLE
[Scriptimprovement] Manual selection of specific Points

### ISSUE THREAD

**Issue by Rushor** [malcrom/WaypointCreator#6]
Suggestion:
Topic:
It would be very comfotable if we would have the ability to select specific waypoints on the map in order to generate a path with only a few number of waypoints

Why is this change needed?
While sniffing the creatures sends a lot of movementpackets. F.ex: For a normal circle route we get 90 -150 points, but we only needs ~10 in order to make the pah look nice.

How should this be realised?
There is no special wish how this should be done, the mainsuggestion is that we want the ability to generate paths with a reduced number of points - either there can be a checkbox for the points, or the possibility to add points manually on the map (dunno whats easier to script)

maybe it can be done like this: http://www.bilder-upload.eu/show.php?file=62a9dc-1433333460.png

**Comment by Rushor** [comment]
solved with https://github.com/Kittnz/WaypointCreator/commit/9853a44279d8ec5afd8b6a91655ae62bb11b704b - very nice :)

**Comment by malcrom** [comment]
I removed the adding spline points.
