### ISSUE TITLE
Legacy

### ISSUE THREAD

**Issue by MehdiAria** [malcrom/WaypointCreator#7]
Is this tool usable for old expansions such as WOTLK and CATA?

**Comment by Kittnz** [comment]
You mean for sniffs from the woltk and cata era? It should.

**Comment by MehdiAria** [comment]
Well I just tried to connect it to my 3.3.5 DB and I got this error after clicking on "connect":
http://i.imgur.com/k5HFyXp.jpg

**Comment by Kittnz** [comment]
works for me, you can always use it without the database.
