### ISSUE TITLE
UDB format: Creature update SQL

### ISSUE THREAD

**Issue by Saben65** [malcrom/WaypointCreator#9]
Currently, in the the output is

```SQL
UPDATE `creature` SET `position_x`=#####,`position_y`=#####,`position_z`=##### WHERE `guid`=@GUID;
```

It is missing the `MovementType` update to 2. Additionally, it appears to selecting the coords of the second WP to use for spawn location of the creature, unlike TDB format which uses the first WP's coords.

**Comment by malcrom** [comment]
Fixed https://github.com/malcrom/WaypointCreator/commit/b6bc8b7faccf5d9764273b9e4a74b0cbba9d341b
